language: node_js
node_js:
  - "6"
  - "7"
  - "8"
script:
  - npm test
before_install:
  - "npm install react prop-types"
after_success:
  - npm run test:coverage
  - coveralls < coverage/lcov.info
  - rm -rf ./coverage
