language: node_js
node_js:
  - "6"
  - "7"
  - "8"
script:
  - npm test
before_install:
  - "npm install react prop-types"
after_success:
  - npm run test:coverage
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - rm -rf ./coverage
